tagline: "Zero-knowledge sync for local-first apps"
description: >
  The relay never sees your data. Not encrypted-at-rest-but-we-have-the-keys.
  Actually zero knowledge. The relay is a dumb pipe that routes ciphertext
  between your devices. No accounts, no key escrow. Keys derive from your
  passphrase via Argon2id. Pure Rust, no runtime, designed for edge hardware,
  slow networks, and battery-constrained devices.
status: development
icon: 0k-sync.svg
tech:
  - Rust
  - iroh
  - QUIC
  - XChaCha20-Poly1305
  - Argon2id
  - BLAKE3
highlights:
  - "Zero-knowledge relay — the server can't read your data, even if compromised"
  - "No accounts — devices pair via passphrase or QR code"
  - "Multi-relay failover — connect failover, push fan-out, per-relay cursor tracking"
  - "530 tests (478 Rust + 21 JS + 31 Python) with 63 chaos scenarios (35 distributed + 28 Docker)"
  - "Relay observability — 14 Prometheus metrics, JSON health endpoint, per-request debug logging"
  - "Transport-agnostic core — sync-types and sync-core have zero iroh dependencies"
  - "Multi-language bindings — Node.js/Bun (napi-rs) and Python (PyO3)"
  - "Large file support with content-addressed hashing (BLAKE3) and chunked transfer"
