/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Configuration for creating a SyncClient. */
export interface JsSyncConfig {
  /** Passphrase for Argon2id key derivation. */
  passphrase?: string
  /** Salt for Argon2id derivation (required with passphrase). */
  salt?: Buffer
  /** Pre-derived 32-byte secret. */
  secretBytes?: Buffer
  /** Relay addresses (iroh NodeIds). First is primary. */
  relayAddresses: Array<string>
  /** Human-readable device name. */
  deviceName?: string
  /** Time-to-live for pushed blobs (seconds, 0 = no expiry). */
  ttl?: number
}
/** Result of a push operation. */
export interface JsPushResult {
  /** The blob identifier (UUID string). */
  blobId: string
  /** The assigned cursor position. */
  cursor: number
}
/** A received blob from a pull operation. */
export interface JsSyncBlob {
  /** The blob identifier (UUID string). */
  blobId: string
  /** The decrypted payload bytes. */
  data: Buffer
  /** The cursor position. */
  cursor: number
  /** Original timestamp. */
  timestamp: number
}
/** An invite for sharing group access. */
export interface JsSyncInvite {
  /** Invite format version. */
  version: number
  /** Relay addresses. */
  relayAddresses: Array<string>
  /** The group secret bytes (32 bytes). */
  groupSecret: Buffer
  /** Argon2id salt. */
  salt: Buffer
  /** QR payload string (base64-encoded JSON). */
  qrPayload: string
  /** Short code (XXXX-XXXX-XXXX-XXXX). */
  shortCode: string
}
/** Result of deriving a group secret. */
export interface JsDeriveResult {
  /** The 32-byte derived secret. */
  secretBytes: Buffer
  /** The 32-byte group identifier. */
  groupId: Buffer
}
/** Decode an invite from a QR payload string. */
export declare function inviteFromQr(payload: string): JsSyncInvite
/**
 * Derive a group secret from a passphrase and salt.
 *
 * Returns the 32-byte secret and 32-byte group ID.
 */
export declare function deriveSecret(passphrase: string, salt: Buffer): JsDeriveResult
/**
 * The main sync client for JavaScript/TypeScript.
 *
 * All async methods return Promises. Create via `SyncClient.create()`.
 */
export declare class SyncClient {
  /**
   * Create a new SyncClient from configuration.
   *
   * This binds a real iroh endpoint (async, may take 0-3s).
   */
  static create(config: JsSyncConfig): Promise<SyncClient>
  /** Check if connected to a relay. */
  isConnected(): Promise<boolean>
  /** Get the current cursor position. */
  currentCursor(): Promise<number>
  /** Get the address of the active relay (if connected). */
  activeRelay(): Promise<string | null>
  /** Connect to the relay(s). */
  connect(): Promise<void>
  /** Disconnect from the relay. */
  disconnect(): Promise<void>
  /** Push encrypted data to the sync group. */
  push(data: Buffer): Promise<JsPushResult>
  /** Pull new blobs from the sync group. */
  pull(): Promise<Array<JsSyncBlob>>
  /** Pull blobs after a specific cursor. */
  pullAfter(cursor: number): Promise<Array<JsSyncBlob>>
  /** Create an invite for sharing group access. */
  createInvite(relayAddresses: Array<string>): JsSyncInvite
  /** Disconnect and release resources. */
  shutdown(): Promise<void>
}
